### ISSUE TITLE
Question regarding portrait mode

### ISSUE THREAD

**Issue by SashaBes** [keijiro/Bibcam#7] opened 2021-12-09 20:40 UTC
Hi! I just wanted to ask if you considering making Bibcam also available for recording in portrait mode?

**Comment by keijiro** [comment] 2021-12-10 12:30
No, there is no plan for adding portrait mode because I don't need it.

At the moment, I have never confirmed the existence of a user of this app excepting me, so I drive the development only by my need.

Or... are you using it?

**Comment by SashaBes** [comment] 2021-12-10 13:15
Thank you for the quick response. And yes, I am trying to use it in my student project. Before you created this app I was trying for month to achieve something similar, but as a person with design and not programming background I was just creating some frankensteins. So it was a real miracle for me when I found your project :D But I am trying to place this functionality to a standalone mobile app, so you can record a video a choose the degree of abstraction from predefined settings.

**Comment by keijiro** [comment] 2021-12-11 03:39
Thanks for the clarification.

Just out of curiosity, why are you prefer portrait than landscape? Bibcam is an app for video post-processing, and in most cases post-processing is done in landscape (widescreen) aspect ratio. That's why I hardcoded the aspect ratio in the format.

**Comment by SashaBes** [comment] 2021-12-11 08:48
A part of my project is creating custom storytelling tools, that would allow a person record a video of themselves and choose a degree of abstraction (=anonymity) by choosing from vfx settings. And this would just be better in a portrait mode (ofc even better with a front camera, but from what I could find Unity does not provide access to the whole functionality of iOS front camera, so I am kind of taking what I can) 

Could you maybe give me some clues? So if I want to add a portrait mode to the Bibcam, would it be relatively simple to do by changing the lines that calculate the aspect ratio etc. or it requires some big complex changing?

**Comment by keijiro** [comment] 2021-12-11 09:30
> A part of my project is creating custom storytelling tools, that would allow a person record a video of themselves and choose a degree of abstraction (=anonymity) by choosing from vfx settings.

I'm afraid that you misunderstood the functionality of Bibcam. It's just a simple video recorder with metadata (like [this](https://user-images.githubusercontent.com/343936/142789292-9bba9330-0fa0-49f8-b270-9bcefe326278.png)) and doesn't contain any VFX.

> what I could find Unity does not provide access to the whole functionality of iOS front camera, so I am kind of taking what I can)

iPhone only has the LIDAR sensor on its rear side. The TrueDepth sensor (on the front side) is a different technology, which is not sufficient for VFX.

> it requires some big complex changing?

Yes, it requires big complex changes.

**Comment by SashaBes** [comment] 2021-12-11 09:43
Thanks for the clarification! Probably my explanations were a bit misleading, I am using Bibcam together with Unity VFX, like in your Bibcam VFX repo, but I am creating predefined vfx settings that user can choose from directly on the phone.

**Comment by keijiro** [comment] 2021-12-11 16:33
I understood. Anyway, my last answer would be the most important -- It requires big changes. Unfortunately, I don't have time for it. I should invest time for exploring the possibility of Bibcam with several VFX ideas.

**Comment by SashaBes** [comment] 2021-12-11 20:40
Sure I understand!

**Comment by keijiro** [comment] 2021-12-13 08:43
I'm closing this issue now. Please feel free to reopen it for further problems.

**Closed by keijiro** 2021-12-13 08:43 UTC
Labels: question
